language: node_js
node_js:
  - 'stable'
  - '8'
script:
  - 'npm run build'
  - 'npm test'
after_script:
  - ls -lh index.json
before_deploy:
  - npm version --no-git-tag-version --force $(npx semver -- -i minor $(npm info german-postal-codes version))
deploy:
  provider: npm
  on:
    branch: master
    node: stable
  email: 'mail@jannisr.de'
  api_key: ${NPM_KEY}
  skip_cleanup: true
