sudo: false
language: node_js
node_js:
  - 'stable'
  - '7'
  - '6'
script:
  - 'npm run build'
  - 'npm test'
after_script:
  - ls -lh index.json
deploy:
  provider: npm
  on:
    branch: master
    node: latest
  email: 'mail@jannisr.de'
  api_key: ${NPM_KEY}
  skip_cleanup: true
